# Generated by Django 4.1.7 on 2023-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hyperlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
