# Generated by Django 4.1.7 on 2023-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hyperlist", "0002_originurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="hyperlink",
            name="text",
            field=models.CharField(
                default=models.CharField(max_length=200), max_length=200
            ),
        ),
    ]
